module.exports = {
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^~/(.*)$': '<rootDir>/src/$1',
    '^vue$': 'vue/dist/vue.common.js',
  },
  moduleFileExtensions: ['ts', 'js', 'vue', 'json'],
  testMatch: ['<rootDir>/__tests__/**/*.{spec,test}.{js,ts}'],
  transform: {
    '^.+\\.ts$': 'ts-jest',
    '^.+\\.js$': 'babel-jest',
    '.*\\.(vue)$': 'vue-jest',
  },
  collectCoverage: true,
  collectCoverageFrom: ['<rootDir>/src/components/**/*.vue', '<rootDir>/src/pages/**/*.vue', '<rootDir>/src/utils/**/*.{js,ts}'],
  testEnvironment: 'jsdom',
  preset: 'ts-jest',
  testPathIgnorePatterns: [
    '/.next/',
    '/.nuxt/',
    '/node_modules/',
    '/_node_modules/',
    '/__node_modules/',
    '/lib/',
    '/tests/',
    '/coverage/',
    '/.storybook/',
    '/.husky/',
    '/.vscode/',
    '/cypress/',
    '/config/',
    '/public/',
    '/dist/',
    '/build/',
  ],
  transformIgnorePatterns: ['<rootDir>/node_modules/'],
}
